/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/pricing/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simula a precificação de um recebível (não persiste nada)
         * @description valorPresente = valorFace / (1 + taxaBase + spread) ^ (prazoDias / 30); conversão cambial aplicada no final sobre o valor não arredondado; arredondamento HALF_EVEN único.
         */
        post: operations["simulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de taxas de um par (mais recente primeiro) */
        get: operations["history"];
        put?: never;
        /** Cadastra uma taxa manualmente */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sincroniza as taxas com a API Frankfurter
         * @description Chamada protegida por retry e circuit breaker. Idempotente: taxas idênticas não são duplicadas. 503 FX_PROVIDER_UNAVAILABLE se o provedor estiver indisponível.
         */
        post: operations["synchronize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria uma operação de cessão (precifica e persiste o lote atomicamente)
         * @description 201 para uma nova operação. Com Idempotency-Key: a mesma chave com o mesmo conteúdo devolve a operação existente (200); com outro conteúdo, 409 IDEMPOTENCY_KEY_REUSED.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit-assignments/{id}/settlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Liquida a operação (If-Match obrigatório)
         * @description Na mesma transação: PENDING -> SETTLED, débito da conta-caixa do fundo na moeda de pagamento e registro do movimento. 409 se já liquidada/cancelada ou em conflito concorrente, 412 se o If-Match não for a versão atual, 422 INSUFFICIENT_FUNDS, 428 sem If-Match.
         */
        post: operations["settle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit-assignments/{id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela uma operação pendente (If-Match obrigatório) */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pesquisa cedentes por nome ou início do CNPJ */
        get: operations["search"];
        put?: never;
        /** Cadastra um cedente (CNPJ único) */
        post: operations["register_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/settlement-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extrato de liquidação / histórico de operações
         * @description Filtros opcionais por período (datas de negócio, inclusivas), cedente, moeda de pagamento e status; paginação no servidor; ordenação por whitelist (createdAt, settledAt, totalNetAmount, assignorName).
         */
        get: operations["statement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receivable-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tipos de recebível ativos com o spread mensal da Strategy de cada tipo */
        get: operations["receivableTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta uma taxa pelo identificador */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxa vigente de um par
         * @description Usa o par publicado ou o inverso derivado, o que for mais recente. 404 se não houver taxa.
         */
        get: operations["latest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as moedas suportadas */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit-assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta uma operação (ETag = versão atual) */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saldo das contas-caixa do fundo */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta um cedente */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FieldViolation: {
            /** @description Campo inválido (ex.: receivables[0].faceValue) */
            field: string;
            /** @description Mensagem de validação, em português */
            message: string;
        };
        /** @description Problem Details (RFC 9457) com as extensões code, correlationId e errors */
        Problem: {
            /**
             * Format: uri
             * @description URI que identifica o tipo do problema
             */
            type: string;
            /** @description Resumo do problema, em português */
            title: string;
            /** @description Status HTTP */
            status: number;
            /** @description Explicação desta ocorrência, em português */
            detail?: string;
            /**
             * Format: uri-reference
             * @description Caminho da requisição
             */
            instance?: string;
            /** @description Código estável do erro para tratamento no cliente (ex.: INSUFFICIENT_FUNDS) */
            code: string;
            /** @description Mesmo valor do header X-Correlation-Id e dos logs */
            correlationId: string;
            /** @description Violações por campo (somente em erros de validação) */
            errors?: components["schemas"]["FieldViolation"][];
        };
        SimulationRequest: {
            /** @example DUPLICATA_MERCANTIL */
            receivableType: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            faceValue: string;
            /**
             * @example BRL
             * @enum {string}
             */
            faceCurrency: "BRL" | "USD";
            /**
             * Format: date
             * @example 2026-12-22
             */
            dueDate: string;
            /**
             * @example USD
             * @enum {string}
             */
            paymentCurrency: "BRL" | "USD";
        };
        ExchangeRateSnapshot: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            base: "BRL" | "USD";
            /** @enum {string} */
            quote: "BRL" | "USD";
            /**
             * Format: decimal
             * @example 10000.00
             */
            rate: string;
            /** Format: date */
            referenceDate: string;
        };
        SimulationResponse: {
            /** @enum {string} */
            receivableType: "DUPLICATA_MERCANTIL" | "CHEQUE_PRE_DATADO";
            /**
             * Format: decimal
             * @example 10000.00
             */
            faceValue: string;
            /** @enum {string} */
            faceCurrency: "BRL" | "USD";
            /** @enum {string} */
            paymentCurrency: "BRL" | "USD";
            /** Format: date */
            operationDate: string;
            /** Format: date */
            dueDate: string;
            /** Format: int32 */
            termDays: number;
            /**
             * Format: decimal
             * @description termDays / 30
             * @example 10000.00
             */
            termMonths: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            baseRate: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            spread: string;
            /**
             * Format: decimal
             * @description baseRate + spread (mensal)
             * @example 10000.00
             */
            discountRate: string;
            /**
             * Format: decimal
             * @description Na moeda de face
             * @example 10000.00
             */
            presentValue: string;
            /**
             * Format: decimal
             * @description Na moeda de face
             * @example 10000.00
             */
            discount: string;
            /** @description null quando faceCurrency == paymentCurrency */
            exchangeRate: components["schemas"]["ExchangeRateSnapshot"] | null;
            /**
             * Format: decimal
             * @description Valor presente na moeda de pagamento
             * @example 10000.00
             */
            netAmount: string;
        };
        ManualExchangeRateRequest: {
            /**
             * @example USD
             * @enum {string}
             */
            base: "BRL" | "USD";
            /**
             * @example BRL
             * @enum {string}
             */
            quote: "BRL" | "USD";
            /**
             * Format: decimal
             * @example 5.2000
             */
            rate: string;
            /**
             * Format: date
             * @example 2026-09-23
             */
            referenceDate?: string;
        };
        ExchangeRateResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            base: "BRL" | "USD";
            /** @enum {string} */
            quote: "BRL" | "USD";
            /**
             * Format: decimal
             * @description Unidades de quote por 1 unidade de base
             * @example 5.13220000
             */
            rate: string;
            /** @enum {string} */
            source: "MANUAL" | "FRANKFURTER" | "SEED";
            /** Format: date */
            referenceDate: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Taxa mais antiga que srm.fx.max-rate-age; não pode precificar operações */
            stale: boolean;
            /** @description Taxa derivada do par inverso (ex.: BRL/USD calculada a partir de USD/BRL) */
            derived: boolean;
        };
        CreateCreditAssignmentRequest: {
            /** Format: uuid */
            assignorId: string;
            /**
             * @example BRL
             * @enum {string}
             */
            paymentCurrency: "BRL" | "USD";
            receivables: components["schemas"]["ReceivableRequest"][];
        };
        ReceivableRequest: {
            /** @example DUPLICATA_MERCANTIL */
            receivableType: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            faceValue: string;
            /**
             * @example BRL
             * @enum {string}
             */
            faceCurrency: "BRL" | "USD";
            /**
             * Format: date
             * @example 2026-12-22
             */
            dueDate: string;
        };
        AssignorSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            document: string;
        };
        CreditAssignmentResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING" | "SETTLED" | "CANCELLED";
            /**
             * Format: int64
             * @description Versão para controle otimista (também devolvida no ETag)
             */
            version: number;
            assignor: components["schemas"]["AssignorSummary"];
            /** @enum {string} */
            paymentCurrency: "BRL" | "USD";
            /**
             * Format: decimal
             * @example 10000.00
             */
            totalFaceValue: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            totalDiscount: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            totalNetAmount: string;
            /** Format: int32 */
            receivablesCount: number;
            receivables: components["schemas"]["ReceivableResponse"][];
            /** Format: date-time */
            createdAt: string;
            settledAt: string | null;
            cancelledAt: string | null;
        };
        ReceivableResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            receivableType: "DUPLICATA_MERCANTIL" | "CHEQUE_PRE_DATADO";
            /**
             * Format: decimal
             * @example 10000.00
             */
            faceValue: string;
            /** @enum {string} */
            faceCurrency: "BRL" | "USD";
            /** Format: date */
            dueDate: string;
            /** Format: int32 */
            termDays: number;
            /**
             * Format: decimal
             * @example 10000.00
             */
            baseRate: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            spread: string;
            /**
             * Format: decimal
             * @description Na moeda de face
             * @example 10000.00
             */
            presentValue: string;
            /**
             * Format: decimal
             * @description Na moeda de face
             * @example 10000.00
             */
            discount: string;
            /** @description null quando a moeda de face é a de pagamento */
            exchangeRate: components["schemas"]["ExchangeRateSnapshot"] | null;
            /**
             * Format: decimal
             * @description Na moeda de pagamento
             * @example 10000.00
             */
            netAmount: string;
        };
        AssignorRequest: {
            /** @example ACME Indústria Ltda */
            name: string;
            /** @example 11222333000181 */
            document: string;
        };
        AssignorResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            document: string;
            /** Format: date-time */
            createdAt: string;
        };
        PageMetadata: {
            /** Format: int32 */
            number: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseSettlementStatementItem: {
            content: components["schemas"]["SettlementStatementItem"][];
            page: components["schemas"]["PageMetadata"];
        };
        SettlementStatementItem: {
            /** Format: uuid */
            operationId: string;
            /** Format: uuid */
            assignorId: string;
            assignorName: string;
            assignorDocument: string;
            /** @enum {string} */
            status: "PENDING" | "SETTLED" | "CANCELLED";
            /** @enum {string} */
            paymentCurrency: "BRL" | "USD";
            /** Format: int32 */
            receivablesCount: number;
            /**
             * Format: decimal
             * @example 10000.00
             */
            totalFaceValue: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            totalDiscount: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            totalNetAmount: string;
            /** Format: date-time */
            createdAt: string;
            settledAt: string | null;
        };
        ReceivableTypeResponse: {
            /** @enum {string} */
            code: "DUPLICATA_MERCANTIL" | "CHEQUE_PRE_DATADO";
            description: string;
            /**
             * Format: decimal
             * @example 10000.00
             */
            monthlySpread: string;
        };
        PageResponseExchangeRateResponse: {
            content: components["schemas"]["ExchangeRateResponse"][];
            page: components["schemas"]["PageMetadata"];
        };
        CurrencyResponse: {
            /** @enum {string} */
            code: "BRL" | "USD";
            name: string;
            /** Format: int32 */
            decimals: number;
        };
        CashAccountResponse: {
            /** @enum {string} */
            currency: "BRL" | "USD";
            /**
             * Format: decimal
             * @example 10000.00
             */
            balance: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PageResponseAssignorResponse: {
            content: components["schemas"]["AssignorResponse"][];
            page: components["schemas"]["PageMetadata"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Regra de negócio violada */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    history: {
        parameters: {
            query: {
                /** @example USD */
                base: "BRL" | "USD";
                /** @example BRL */
                quote: "BRL" | "USD";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseExchangeRateResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualExchangeRateRequest"];
            };
        };
        responses: {
            /** @description Taxa registrada */
            201: {
                headers: {
                    /** @description URL da taxa criada */
                    Location?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    synchronize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateResponse"][];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Provedor de câmbio indisponível (circuit breaker aberto ou falha após retries) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Chave de idempotência (UUID recomendado) */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCreditAssignmentRequest"];
            };
        };
        responses: {
            /** @description Reenvio idempotente: a mesma Idempotency-Key e o mesmo conteúdo devolvem a operação já criada */
            200: {
                headers: {
                    /** @description Versão atual da operação */
                    ETag?: unknown;
                    /** @description URL da operação existente */
                    "Content-Location"?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditAssignmentResponse"];
                };
            };
            /** @description Operação criada (PENDING) */
            201: {
                headers: {
                    /** @description Versão da operação, ex.: "0" */
                    ETag?: unknown;
                    /** @description URL da operação criada */
                    Location?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditAssignmentResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflito de estado (operação já liquidada/cancelada, concorrência, duplicidade) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Regra de negócio violada */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    settle: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag atual da operação, ex.: "0" */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operação liquidada (SETTLED) */
            200: {
                headers: {
                    /** @description Nova versão da operação */
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditAssignmentResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflito de estado (operação já liquidada/cancelada, concorrência, duplicidade) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description If-Match não corresponde à versão atual do recurso */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Regra de negócio violada */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description If-Match ausente */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag atual da operação, ex.: "0" */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operação cancelada (CANCELLED) */
            200: {
                headers: {
                    /** @description Nova versão da operação */
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditAssignmentResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflito de estado (operação já liquidada/cancelada, concorrência, duplicidade) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description If-Match não corresponde à versão atual do recurso */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description If-Match ausente */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                search?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseAssignorResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    register_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignorRequest"];
            };
        };
        responses: {
            /** @description Cedente cadastrado */
            201: {
                headers: {
                    /** @description URL do cedente criado */
                    Location?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignorResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflito de estado (operação já liquidada/cancelada, concorrência, duplicidade) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    statement: {
        parameters: {
            query?: {
                /** @example 2026-09-01 */
                from?: string | null;
                /** @example 2026-09-30 */
                to?: string | null;
                assignorId?: string | null;
                currency?: "BRL" | "USD" | null;
                status?: "PENDING" | "SETTLED" | "CANCELLED" | null;
                page?: number | null;
                size?: number | null;
                /** @description Campos: createdAt, settledAt, totalNetAmount, assignorName; direção asc|desc */
                sort?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseSettlementStatementItem"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    receivableTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivableTypeResponse"][];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    latest: {
        parameters: {
            query: {
                /** @example USD */
                base: "BRL" | "USD";
                /** @example BRL */
                quote: "BRL" | "USD";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyResponse"][];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operação */
            200: {
                headers: {
                    /** @description Versão atual, usada no If-Match */
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditAssignmentResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashAccountResponse"][];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignorResponse"];
                };
            };
            /** @description Requisição inválida (validação, formato ou parâmetro) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erro inesperado (sem detalhes internos) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
