-- =====================================================================================
-- SRM Credit Engine - base schema
--
-- Conventions
--   * Money is NUMERIC(19,2) and rates are NUMERIC(19,8): exact decimal arithmetic, never
--     floating point.
--   * Every timestamp is TIMESTAMPTZ (an absolute instant, stored in UTC).
--   * Surrogate keys are UUIDs generated by the application (version 7, time ordered, so
--     B-tree inserts stay append-mostly like a sequence).
--   * Codes (currency, status, type) are VARCHAR + CHECK instead of CHAR(n): no blank
--     padding semantics and a 1:1 mapping to the Java enums.
--   * Business rules are enforced by the domain model AND by the constraints below
--     (defense in depth): a bug in the application must not corrupt the ledger.
-- =====================================================================================

-- -------------------------------------------------------------------------------------
-- Reference data
-- -------------------------------------------------------------------------------------

CREATE TABLE currency
(
    code     VARCHAR(3)  NOT NULL,
    name     VARCHAR(60) NOT NULL,
    decimals SMALLINT    NOT NULL,
    CONSTRAINT pk_currency PRIMARY KEY (code),
    CONSTRAINT ck_currency_code_iso4217 CHECK (code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_currency_decimals CHECK (decimals BETWEEN 0 AND 4)
);
COMMENT ON TABLE currency IS 'ISO-4217 currencies the fund operates with (payment and face currencies).';
COMMENT ON COLUMN currency.decimals IS 'Minor units used when rounding amounts expressed in this currency.';

CREATE TABLE receivable_type
(
    code        VARCHAR(40)  NOT NULL,
    description VARCHAR(120) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_receivable_type PRIMARY KEY (code)
);
COMMENT ON TABLE receivable_type IS 'Receivable products. The risk spread of each type lives in a pricing strategy (code), not here.';

-- -------------------------------------------------------------------------------------
-- Currency engine: append-only exchange rate history
-- -------------------------------------------------------------------------------------

CREATE TABLE exchange_rate
(
    id             UUID          NOT NULL,
    base_currency  VARCHAR(3)    NOT NULL,
    quote_currency VARCHAR(3)    NOT NULL,
    rate           NUMERIC(19, 8) NOT NULL,
    source         VARCHAR(20)   NOT NULL,
    reference_date DATE          NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_exchange_rate PRIMARY KEY (id),
    CONSTRAINT fk_exchange_rate_base_currency FOREIGN KEY (base_currency) REFERENCES currency (code),
    CONSTRAINT fk_exchange_rate_quote_currency FOREIGN KEY (quote_currency) REFERENCES currency (code),
    CONSTRAINT ck_exchange_rate_positive CHECK (rate > 0),
    CONSTRAINT ck_exchange_rate_distinct_currencies CHECK (base_currency <> quote_currency),
    CONSTRAINT ck_exchange_rate_source CHECK (source IN ('MANUAL', 'FRANKFURTER', 'SEED'))
);
COMMENT ON TABLE exchange_rate IS 'Append-only FX history. Rows are never updated so every priced receivable can reference the exact rate it used.';
COMMENT ON COLUMN exchange_rate.rate IS 'Units of quote_currency worth one unit of base_currency (USD/BRL 5.1322 => 1 USD = 5.1322 BRL).';
COMMENT ON COLUMN exchange_rate.reference_date IS 'Business date the rate refers to (e.g. the ECB publication date).';

-- "Latest rate of a pair" is an index-only descent on this index.
CREATE INDEX ix_exchange_rate_pair_latest
    ON exchange_rate (base_currency, quote_currency, reference_date DESC, created_at DESC);
CREATE INDEX ix_exchange_rate_quote_currency ON exchange_rate (quote_currency);

-- -------------------------------------------------------------------------------------
-- Assignors (cedentes)
-- -------------------------------------------------------------------------------------

CREATE TABLE assignor
(
    id         UUID         NOT NULL,
    name       VARCHAR(150) NOT NULL,
    document   VARCHAR(14)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_assignor PRIMARY KEY (id),
    CONSTRAINT uk_assignor_document UNIQUE (document),
    CONSTRAINT ck_assignor_document_digits CHECK (document ~ '^[0-9]{14}$')
);
COMMENT ON COLUMN assignor.document IS 'CNPJ, digits only (check digits are validated by the application).';

-- -------------------------------------------------------------------------------------
-- Credit assignment operations (aggregate root) and their receivables
-- -------------------------------------------------------------------------------------

CREATE TABLE credit_assignment
(
    id                UUID           NOT NULL,
    assignor_id       UUID           NOT NULL,
    payment_currency  VARCHAR(3)     NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    total_face_value  NUMERIC(19, 2) NOT NULL,
    total_discount    NUMERIC(19, 2) NOT NULL,
    total_net_amount  NUMERIC(19, 2) NOT NULL,
    receivables_count INTEGER        NOT NULL,
    idempotency_key   VARCHAR(100),
    request_hash      VARCHAR(64),
    version           BIGINT         NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    settled_at        TIMESTAMPTZ,
    cancelled_at      TIMESTAMPTZ,
    CONSTRAINT pk_credit_assignment PRIMARY KEY (id),
    CONSTRAINT fk_credit_assignment_assignor FOREIGN KEY (assignor_id) REFERENCES assignor (id),
    CONSTRAINT fk_credit_assignment_payment_currency FOREIGN KEY (payment_currency) REFERENCES currency (code),
    CONSTRAINT uk_credit_assignment_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_credit_assignment_status CHECK (status IN ('PENDING', 'SETTLED', 'CANCELLED')),
    CONSTRAINT ck_credit_assignment_totals CHECK (
        total_face_value > 0
            AND total_discount >= 0
            AND total_net_amount >= 0
            AND total_face_value = total_discount + total_net_amount),
    CONSTRAINT ck_credit_assignment_receivables_count CHECK (receivables_count > 0),
    CONSTRAINT ck_credit_assignment_idempotency CHECK ((idempotency_key IS NULL) = (request_hash IS NULL)),
    -- The lifecycle timestamps must agree with the status (PENDING -> SETTLED | CANCELLED).
    CONSTRAINT ck_credit_assignment_lifecycle CHECK (
        (status = 'PENDING' AND settled_at IS NULL AND cancelled_at IS NULL)
            OR (status = 'SETTLED' AND settled_at IS NOT NULL AND cancelled_at IS NULL)
            OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND settled_at IS NULL))
);
COMMENT ON TABLE credit_assignment IS 'Credit assignment operation (batch of receivables bought from an assignor).';
COMMENT ON COLUMN credit_assignment.total_face_value IS 'Sum of face values converted to the payment currency (denormalized for the statement report).';
COMMENT ON COLUMN credit_assignment.total_net_amount IS 'Amount paid to the assignor in the payment currency (sum of receivable net amounts).';
COMMENT ON COLUMN credit_assignment.request_hash IS 'SHA-256 of the canonical creation request, used to detect Idempotency-Key reuse with another payload.';
COMMENT ON COLUMN credit_assignment.version IS 'Optimistic locking version, exposed to clients as the ETag.';

-- Statement report access paths: every filter combination is served by an index that is
-- already ordered by the default sort (created_at DESC, id DESC as tie breaker).
CREATE INDEX ix_credit_assignment_created_at ON credit_assignment (created_at DESC, id DESC);
CREATE INDEX ix_credit_assignment_assignor_created_at ON credit_assignment (assignor_id, created_at DESC);
CREATE INDEX ix_credit_assignment_currency_created_at ON credit_assignment (payment_currency, created_at DESC);
CREATE INDEX ix_credit_assignment_status_created_at ON credit_assignment (status, created_at DESC);

CREATE TABLE receivable
(
    id                    UUID           NOT NULL,
    credit_assignment_id  UUID           NOT NULL,
    type_code             VARCHAR(40)    NOT NULL,
    face_value            NUMERIC(19, 2) NOT NULL,
    face_currency         VARCHAR(3)     NOT NULL,
    due_date              DATE           NOT NULL,
    term_days             INTEGER        NOT NULL,
    base_rate             NUMERIC(19, 8) NOT NULL,
    spread                NUMERIC(19, 8) NOT NULL,
    present_value         NUMERIC(19, 2) NOT NULL,
    discount              NUMERIC(19, 2) NOT NULL,
    exchange_rate_id      UUID,
    exchange_rate_applied NUMERIC(19, 8),
    net_amount            NUMERIC(19, 2) NOT NULL,
    CONSTRAINT pk_receivable PRIMARY KEY (id),
    CONSTRAINT fk_receivable_credit_assignment FOREIGN KEY (credit_assignment_id) REFERENCES credit_assignment (id),
    CONSTRAINT fk_receivable_type FOREIGN KEY (type_code) REFERENCES receivable_type (code),
    CONSTRAINT fk_receivable_face_currency FOREIGN KEY (face_currency) REFERENCES currency (code),
    CONSTRAINT fk_receivable_exchange_rate FOREIGN KEY (exchange_rate_id) REFERENCES exchange_rate (id),
    CONSTRAINT ck_receivable_face_value_positive CHECK (face_value > 0),
    CONSTRAINT ck_receivable_term_positive CHECK (term_days > 0),
    CONSTRAINT ck_receivable_rates_non_negative CHECK (base_rate >= 0 AND spread >= 0),
    CONSTRAINT ck_receivable_amounts CHECK (
        present_value >= 0
            AND discount >= 0
            AND net_amount >= 0
            AND face_value = present_value + discount),
    -- Cross-currency items carry a full FX snapshot; same-currency items carry none.
    CONSTRAINT ck_receivable_fx_snapshot CHECK ((exchange_rate_id IS NULL) = (exchange_rate_applied IS NULL))
);
COMMENT ON TABLE receivable IS 'Priced receivable with a full audit snapshot of the rates used (base rate, spread, FX).';
COMMENT ON COLUMN receivable.present_value IS 'face_value / (1 + base_rate + spread) ^ (term_days / 30), in the face currency.';
COMMENT ON COLUMN receivable.exchange_rate_applied IS 'Rate of the referenced exchange_rate row at pricing time (quote per base of that row).';
COMMENT ON COLUMN receivable.net_amount IS 'Present value converted to the payment currency of the operation.';

CREATE INDEX ix_receivable_credit_assignment ON receivable (credit_assignment_id);
CREATE INDEX ix_receivable_exchange_rate ON receivable (exchange_rate_id) WHERE exchange_rate_id IS NOT NULL;
-- type_code / face_currency reference tiny lookup tables whose rows are never deleted,
-- so indexing those foreign keys would only slow down inserts.

-- -------------------------------------------------------------------------------------
-- Fund treasury: one cash account per currency + an append-only ledger
-- -------------------------------------------------------------------------------------

CREATE TABLE fund_cash_account
(
    currency   VARCHAR(3)     NOT NULL,
    balance    NUMERIC(19, 2) NOT NULL,
    version    BIGINT         NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT pk_fund_cash_account PRIMARY KEY (currency),
    CONSTRAINT fk_fund_cash_account_currency FOREIGN KEY (currency) REFERENCES currency (code),
    -- Last line of defense against overdrafts caused by concurrent settlements.
    CONSTRAINT ck_fund_cash_account_balance_non_negative CHECK (balance >= 0)
);
COMMENT ON COLUMN fund_cash_account.version IS 'Optimistic locking version: concurrent debits never overwrite each other.';

CREATE TABLE cash_movement
(
    id                   UUID           NOT NULL,
    currency             VARCHAR(3)     NOT NULL,
    credit_assignment_id UUID,
    amount               NUMERIC(19, 2) NOT NULL,
    direction            VARCHAR(6)     NOT NULL,
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT pk_cash_movement PRIMARY KEY (id),
    CONSTRAINT fk_cash_movement_account FOREIGN KEY (currency) REFERENCES fund_cash_account (currency),
    CONSTRAINT fk_cash_movement_credit_assignment FOREIGN KEY (credit_assignment_id) REFERENCES credit_assignment (id),
    CONSTRAINT ck_cash_movement_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_cash_movement_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    -- Money only leaves the fund to pay for a credit assignment.
    CONSTRAINT ck_cash_movement_debit_has_operation CHECK (direction = 'CREDIT' OR credit_assignment_id IS NOT NULL)
);
COMMENT ON TABLE cash_movement IS 'Append-only ledger of the fund cash accounts.';

-- An operation can be paid only once: a second settlement debit is rejected by the database
-- even if every application-level guard failed. Also serves as the FK index for debits.
CREATE UNIQUE INDEX uq_cash_movement_settlement_debit
    ON cash_movement (credit_assignment_id)
    WHERE direction = 'DEBIT';
CREATE INDEX ix_cash_movement_currency_created_at ON cash_movement (currency, created_at DESC);
