package com.srm.creditengine.domain.assignment;

import static com.srm.creditengine.domain.currency.CurrencyCode.BRL;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.srm.creditengine.domain.assignor.Assignor;
import com.srm.creditengine.domain.common.BusinessClock;
import com.srm.creditengine.domain.common.BusinessProperties;
import com.srm.creditengine.domain.common.ResourceNotFoundException;
import com.srm.creditengine.domain.common.StaleVersionException;
import com.srm.creditengine.domain.treasury.CashMovement;
import com.srm.creditengine.domain.treasury.FundCashAccount;
import com.srm.creditengine.domain.treasury.InsufficientFundsException;
import com.srm.creditengine.domain.treasury.MovementDirection;
import com.srm.creditengine.persistence.CashMovementRepository;
import com.srm.creditengine.persistence.CreditAssignmentRepository;
import com.srm.creditengine.persistence.FundCashAccountRepository;
import java.math.BigDecimal;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.test.util.ReflectionTestUtils;

class SettlementTransactionsTest {

    private static final Instant NOW = Instant.parse("2026-09-23T12:00:00Z");
    private static final UUID ID = UUID.fromString("01996f3c-0000-7000-8000-000000000042");

    private final CreditAssignmentRepository operations = mock(CreditAssignmentRepository.class);
    private final FundCashAccountRepository accounts = mock(FundCashAccountRepository.class);
    private final CashMovementRepository movements = mock(CashMovementRepository.class);
    private final SettlementTransactions transactions = new SettlementTransactions(
            operations,
            accounts,
            movements,
            new BusinessClock(
                    Clock.fixed(NOW, ZoneOffset.UTC), new BusinessProperties(ZoneId.of("America/Sao_Paulo"))));

    /** Operation paid in BRL with a total net amount of 21523.81. */
    private final CreditAssignment operation = CreditAssignment.open(
            Assignor.register("ACME", "11222333000181", NOW), BRL, CreditAssignmentTest.contractExample(), null, NOW);

    SettlementTransactionsTest() {
        // the id is generated by Hibernate on persist; set it as a loaded operation would have it
        ReflectionTestUtils.setField(operation, "id", ID);
    }

    private FundCashAccount accountWith(String balance) {
        FundCashAccount account = new FundCashAccount(BRL, new BigDecimal(balance), NOW.minusSeconds(3600));
        when(accounts.findById(BRL)).thenReturn(Optional.of(account));
        return account;
    }

    @Test
    void settlesDebitsTheFundAndRecordsTheLedgerEntry() {
        when(operations.findAggregateById(ID)).thenReturn(Optional.of(operation));
        FundCashAccount account = accountWith("50000.00");

        CreditAssignment settled = transactions.settle(ID, 0);

        assertThat(settled.getStatus()).isEqualTo(CreditAssignmentStatus.SETTLED);
        assertThat(settled.getSettledAt()).isEqualTo(NOW);
        assertThat(account.getBalance()).isEqualTo(new BigDecimal("28476.19"));
        ArgumentCaptor<CashMovement> movement = ArgumentCaptor.forClass(CashMovement.class);
        verify(movements).save(movement.capture());
        assertThat(movement.getValue().getDirection()).isEqualTo(MovementDirection.DEBIT);
        assertThat(movement.getValue().getAmount()).isEqualTo(new BigDecimal("21523.81"));
        assertThat(movement.getValue().getCurrency()).isEqualTo(BRL);
        assertThat(movement.getValue().getCreditAssignmentId()).isEqualTo(ID);
    }

    @Test
    void insufficientFundsAbortsBeforeRecordingAnything() {
        when(operations.findAggregateById(ID)).thenReturn(Optional.of(operation));
        FundCashAccount account = accountWith("100.00");

        assertThatExceptionOfType(InsufficientFundsException.class).isThrownBy(() -> transactions.settle(ID, 0));
        assertThat(account.getBalance()).isEqualTo(new BigDecimal("100.00"));
        verify(movements, never()).save(any());
    }

    @Test
    void aStaleVersionIsRejectedBeforeAnyChange() {
        when(operations.findAggregateById(ID)).thenReturn(Optional.of(operation));

        assertThatExceptionOfType(StaleVersionException.class).isThrownBy(() -> transactions.settle(ID, 7));
        assertThat(operation.getStatus()).isEqualTo(CreditAssignmentStatus.PENDING);
        verify(accounts, never()).findById(any());
    }

    @Test
    void cancelsAPendingOperationWithoutTouchingTheTreasury() {
        when(operations.findAggregateById(ID)).thenReturn(Optional.of(operation));

        CreditAssignment cancelled = transactions.cancel(ID, 0);

        assertThat(cancelled.getStatus()).isEqualTo(CreditAssignmentStatus.CANCELLED);
        verify(accounts, never()).findById(any());
        verify(movements, never()).save(any());
    }

    @Test
    void unknownOperationIsNotFound() {
        when(operations.findAggregateById(ID)).thenReturn(Optional.empty());

        assertThatExceptionOfType(ResourceNotFoundException.class).isThrownBy(() -> transactions.settle(ID, 0));
        assertThatExceptionOfType(ResourceNotFoundException.class).isThrownBy(() -> transactions.cancel(ID, 0));
    }
}
